export ROBOTPKG_BASE=/opt/openrobots
export PATH=$ROBOTPKG_BASE/bin:$PATH
export PYTHONPATH=$ROBOTPKG_BASE/lib/python3.6/site-packages:$PYTHONPATH
export LD_LIBRARY_PATH=$ROBOTPKG_BASE/lib:$LD_LIBRARY_PATH
export CMAKE_PREFIX_PATH=$ROBOTPKG_BASE:$CMAKE_PREFIX_PATH
export ROS_PACKAGE_PATH=$ROBOTPKG_BASE/share:/opt/ros/melodic/share
